plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
    values:
      image: https://picsum.photos/640/320
author: "Mario Abreu"
